// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.14.0
// source: src/pb/module/common/common.proto

package common

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Format int32

const (
	Format_TEXT   Format = 0
	Format_BINARY Format = 1
)

// Enum value maps for Format.
var (
	Format_name = map[int32]string{
		0: "TEXT",
		1: "BINARY",
	}
	Format_value = map[string]int32{
		"TEXT":   0,
		"BINARY": 1,
	}
)

func (x Format) Enum() *Format {
	p := new(Format)
	*p = x
	return p
}

func (x Format) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Format) Descriptor() protoreflect.EnumDescriptor {
	return file_src_pb_module_common_common_proto_enumTypes[0].Descriptor()
}

func (Format) Type() protoreflect.EnumType {
	return &file_src_pb_module_common_common_proto_enumTypes[0]
}

func (x Format) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Format.Descriptor instead.
func (Format) EnumDescriptor() ([]byte, []int) {
	return file_src_pb_module_common_common_proto_rawDescGZIP(), []int{0}
}

type Lang int32

const (
	Lang_C   Lang = 0
	Lang_WAT Lang = 1
)

// Enum value maps for Lang.
var (
	Lang_name = map[int32]string{
		0: "C",
		1: "WAT",
	}
	Lang_value = map[string]int32{
		"C":   0,
		"WAT": 1,
	}
)

func (x Lang) Enum() *Lang {
	p := new(Lang)
	*p = x
	return p
}

func (x Lang) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Lang) Descriptor() protoreflect.EnumDescriptor {
	return file_src_pb_module_common_common_proto_enumTypes[1].Descriptor()
}

func (Lang) Type() protoreflect.EnumType {
	return &file_src_pb_module_common_common_proto_enumTypes[1]
}

func (x Lang) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Lang.Descriptor instead.
func (Lang) EnumDescriptor() ([]byte, []int) {
	return file_src_pb_module_common_common_proto_rawDescGZIP(), []int{1}
}

type DataField_Type int32

const (
	DataField_BOOL    DataField_Type = 0
	DataField_DATE    DataField_Type = 1
	DataField_INT     DataField_Type = 2
	DataField_INTEGER DataField_Type = 3
	DataField_JSON    DataField_Type = 4
	DataField_JSONB   DataField_Type = 5
	DataField_TEXT    DataField_Type = 6
)

// Enum value maps for DataField_Type.
var (
	DataField_Type_name = map[int32]string{
		0: "BOOL",
		1: "DATE",
		2: "INT",
		3: "INTEGER",
		4: "JSON",
		5: "JSONB",
		6: "TEXT",
	}
	DataField_Type_value = map[string]int32{
		"BOOL":    0,
		"DATE":    1,
		"INT":     2,
		"INTEGER": 3,
		"JSON":    4,
		"JSONB":   5,
		"TEXT":    6,
	}
)

func (x DataField_Type) Enum() *DataField_Type {
	p := new(DataField_Type)
	*p = x
	return p
}

func (x DataField_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DataField_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_src_pb_module_common_common_proto_enumTypes[2].Descriptor()
}

func (DataField_Type) Type() protoreflect.EnumType {
	return &file_src_pb_module_common_common_proto_enumTypes[2]
}

func (x DataField_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DataField_Type.Descriptor instead.
func (DataField_Type) EnumDescriptor() ([]byte, []int) {
	return file_src_pb_module_common_common_proto_rawDescGZIP(), []int{0, 0}
}

type DataField struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string         `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type DataField_Type `protobuf:"varint,2,opt,name=type,proto3,enum=tricorder.pb.module.common.DataField_Type" json:"type,omitempty"`
}

func (x *DataField) Reset() {
	*x = DataField{}
	if protoimpl.UnsafeEnabled {
		mi := &file_src_pb_module_common_common_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DataField) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataField) ProtoMessage() {}

func (x *DataField) ProtoReflect() protoreflect.Message {
	mi := &file_src_pb_module_common_common_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataField.ProtoReflect.Descriptor instead.
func (*DataField) Descriptor() ([]byte, []int) {
	return file_src_pb_module_common_common_proto_rawDescGZIP(), []int{0}
}

func (x *DataField) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DataField) GetType() DataField_Type {
	if x != nil {
		return x.Type
	}
	return DataField_BOOL
}

type Schema struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name   string       `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Fields []*DataField `protobuf:"bytes,2,rep,name=fields,proto3" json:"fields,omitempty"`
}

func (x *Schema) Reset() {
	*x = Schema{}
	if protoimpl.UnsafeEnabled {
		mi := &file_src_pb_module_common_common_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Schema) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Schema) ProtoMessage() {}

func (x *Schema) ProtoReflect() protoreflect.Message {
	mi := &file_src_pb_module_common_common_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Schema.ProtoReflect.Descriptor instead.
func (*Schema) Descriptor() ([]byte, []int) {
	return file_src_pb_module_common_common_proto_rawDescGZIP(), []int{1}
}

func (x *Schema) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Schema) GetFields() []*DataField {
	if x != nil {
		return x.Fields
	}
	return nil
}

var File_src_pb_module_common_common_proto protoreflect.FileDescriptor

var file_src_pb_module_common_common_proto_rawDesc = []byte{
	0x0a, 0x21, 0x73, 0x72, 0x63, 0x2f, 0x70, 0x62, 0x2f, 0x6d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x2f,
	0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x1a, 0x74, 0x72, 0x69, 0x63, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x2e, 0x70,
	0x62, 0x2e, 0x6d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x22,
	0xb0, 0x01, 0x0a, 0x09, 0x44, 0x61, 0x74, 0x61, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x12, 0x12, 0x0a,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x12, 0x3e, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32,
	0x2a, 0x2e, 0x74, 0x72, 0x69, 0x63, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x2e, 0x70, 0x62, 0x2e, 0x6d,
	0x6f, 0x64, 0x75, 0x6c, 0x65, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x44, 0x61, 0x74,
	0x61, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x2e, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70,
	0x65, 0x22, 0x4f, 0x0a, 0x04, 0x54, 0x79, 0x70, 0x65, 0x12, 0x08, 0x0a, 0x04, 0x42, 0x4f, 0x4f,
	0x4c, 0x10, 0x00, 0x12, 0x08, 0x0a, 0x04, 0x44, 0x41, 0x54, 0x45, 0x10, 0x01, 0x12, 0x07, 0x0a,
	0x03, 0x49, 0x4e, 0x54, 0x10, 0x02, 0x12, 0x0b, 0x0a, 0x07, 0x49, 0x4e, 0x54, 0x45, 0x47, 0x45,
	0x52, 0x10, 0x03, 0x12, 0x08, 0x0a, 0x04, 0x4a, 0x53, 0x4f, 0x4e, 0x10, 0x04, 0x12, 0x09, 0x0a,
	0x05, 0x4a, 0x53, 0x4f, 0x4e, 0x42, 0x10, 0x05, 0x12, 0x08, 0x0a, 0x04, 0x54, 0x45, 0x58, 0x54,
	0x10, 0x06, 0x22, 0x5b, 0x0a, 0x06, 0x53, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x12, 0x12, 0x0a, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x12, 0x3d, 0x0a, 0x06, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x25, 0x2e, 0x74, 0x72, 0x69, 0x63, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x2e, 0x70, 0x62, 0x2e,
	0x6d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x44, 0x61,
	0x74, 0x61, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x52, 0x06, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x73, 0x2a,
	0x1e, 0x0a, 0x06, 0x46, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x12, 0x08, 0x0a, 0x04, 0x54, 0x45, 0x58,
	0x54, 0x10, 0x00, 0x12, 0x0a, 0x0a, 0x06, 0x42, 0x49, 0x4e, 0x41, 0x52, 0x59, 0x10, 0x01, 0x2a,
	0x16, 0x0a, 0x04, 0x4c, 0x61, 0x6e, 0x67, 0x12, 0x05, 0x0a, 0x01, 0x43, 0x10, 0x00, 0x12, 0x07,
	0x0a, 0x03, 0x57, 0x41, 0x54, 0x10, 0x01, 0x42, 0x08, 0x5a, 0x06, 0x63, 0x6f, 0x6d, 0x6d, 0x6f,
	0x6e, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_src_pb_module_common_common_proto_rawDescOnce sync.Once
	file_src_pb_module_common_common_proto_rawDescData = file_src_pb_module_common_common_proto_rawDesc
)

func file_src_pb_module_common_common_proto_rawDescGZIP() []byte {
	file_src_pb_module_common_common_proto_rawDescOnce.Do(func() {
		file_src_pb_module_common_common_proto_rawDescData = protoimpl.X.CompressGZIP(file_src_pb_module_common_common_proto_rawDescData)
	})
	return file_src_pb_module_common_common_proto_rawDescData
}

var file_src_pb_module_common_common_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_src_pb_module_common_common_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_src_pb_module_common_common_proto_goTypes = []interface{}{
	(Format)(0),         // 0: tricorder.pb.module.common.Format
	(Lang)(0),           // 1: tricorder.pb.module.common.Lang
	(DataField_Type)(0), // 2: tricorder.pb.module.common.DataField.Type
	(*DataField)(nil),   // 3: tricorder.pb.module.common.DataField
	(*Schema)(nil),      // 4: tricorder.pb.module.common.Schema
}
var file_src_pb_module_common_common_proto_depIdxs = []int32{
	2, // 0: tricorder.pb.module.common.DataField.type:type_name -> tricorder.pb.module.common.DataField.Type
	3, // 1: tricorder.pb.module.common.Schema.fields:type_name -> tricorder.pb.module.common.DataField
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_src_pb_module_common_common_proto_init() }
func file_src_pb_module_common_common_proto_init() {
	if File_src_pb_module_common_common_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_src_pb_module_common_common_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DataField); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_src_pb_module_common_common_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Schema); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_src_pb_module_common_common_proto_rawDesc,
			NumEnums:      3,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_src_pb_module_common_common_proto_goTypes,
		DependencyIndexes: file_src_pb_module_common_common_proto_depIdxs,
		EnumInfos:         file_src_pb_module_common_common_proto_enumTypes,
		MessageInfos:      file_src_pb_module_common_common_proto_msgTypes,
	}.Build()
	File_src_pb_module_common_common_proto = out.File
	file_src_pb_module_common_common_proto_rawDesc = nil
	file_src_pb_module_common_common_proto_goTypes = nil
	file_src_pb_module_common_common_proto_depIdxs = nil
}
