// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.14.0
// source: src/pb/module/wasm/wasm.proto

package wasm

import (
	common "github.com/tricorder/src/pb/module/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Program struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Fmt          common.Format  `protobuf:"varint,1,opt,name=fmt,proto3,enum=tricorder.pb.module.common.Format" json:"fmt,omitempty"`
	Lang         common.Lang    `protobuf:"varint,2,opt,name=lang,proto3,enum=tricorder.pb.module.common.Lang" json:"lang,omitempty"`
	Code         []byte         `protobuf:"bytes,3,opt,name=code,proto3" json:"code,omitempty"`
	FnName       string         `protobuf:"bytes,4,opt,name=fn_name,json=fnName,proto3" json:"fn_name,omitempty"`
	OutputSchema *common.Schema `protobuf:"bytes,5,opt,name=output_schema,json=outputSchema,proto3" json:"output_schema,omitempty"`
}

func (x *Program) Reset() {
	*x = Program{}
	if protoimpl.UnsafeEnabled {
		mi := &file_src_pb_module_wasm_wasm_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Program) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Program) ProtoMessage() {}

func (x *Program) ProtoReflect() protoreflect.Message {
	mi := &file_src_pb_module_wasm_wasm_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Program.ProtoReflect.Descriptor instead.
func (*Program) Descriptor() ([]byte, []int) {
	return file_src_pb_module_wasm_wasm_proto_rawDescGZIP(), []int{0}
}

func (x *Program) GetFmt() common.Format {
	if x != nil {
		return x.Fmt
	}
	return common.Format(0)
}

func (x *Program) GetLang() common.Lang {
	if x != nil {
		return x.Lang
	}
	return common.Lang(0)
}

func (x *Program) GetCode() []byte {
	if x != nil {
		return x.Code
	}
	return nil
}

func (x *Program) GetFnName() string {
	if x != nil {
		return x.FnName
	}
	return ""
}

func (x *Program) GetOutputSchema() *common.Schema {
	if x != nil {
		return x.OutputSchema
	}
	return nil
}

var File_src_pb_module_wasm_wasm_proto protoreflect.FileDescriptor

var file_src_pb_module_wasm_wasm_proto_rawDesc = []byte{
	0x0a, 0x1d, 0x73, 0x72, 0x63, 0x2f, 0x70, 0x62, 0x2f, 0x6d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x2f,
	0x77, 0x61, 0x73, 0x6d, 0x2f, 0x77, 0x61, 0x73, 0x6d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x18, 0x74, 0x72, 0x69, 0x63, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x2e, 0x70, 0x62, 0x2e, 0x6d, 0x6f,
	0x64, 0x75, 0x6c, 0x65, 0x2e, 0x77, 0x61, 0x73, 0x6d, 0x1a, 0x21, 0x73, 0x72, 0x63, 0x2f, 0x70,
	0x62, 0x2f, 0x6d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2f,
	0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xeb, 0x01, 0x0a,
	0x07, 0x50, 0x72, 0x6f, 0x67, 0x72, 0x61, 0x6d, 0x12, 0x34, 0x0a, 0x03, 0x66, 0x6d, 0x74, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x22, 0x2e, 0x74, 0x72, 0x69, 0x63, 0x6f, 0x72, 0x64, 0x65,
	0x72, 0x2e, 0x70, 0x62, 0x2e, 0x6d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x2e, 0x63, 0x6f, 0x6d, 0x6d,
	0x6f, 0x6e, 0x2e, 0x46, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x52, 0x03, 0x66, 0x6d, 0x74, 0x12, 0x34,
	0x0a, 0x04, 0x6c, 0x61, 0x6e, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x20, 0x2e, 0x74,
	0x72, 0x69, 0x63, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x2e, 0x70, 0x62, 0x2e, 0x6d, 0x6f, 0x64, 0x75,
	0x6c, 0x65, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x4c, 0x61, 0x6e, 0x67, 0x52, 0x04,
	0x6c, 0x61, 0x6e, 0x67, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x0c, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x17, 0x0a, 0x07, 0x66, 0x6e, 0x5f, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x66, 0x6e, 0x4e, 0x61, 0x6d,
	0x65, 0x12, 0x47, 0x0a, 0x0d, 0x6f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x5f, 0x73, 0x63, 0x68, 0x65,
	0x6d, 0x61, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x22, 0x2e, 0x74, 0x72, 0x69, 0x63, 0x6f,
	0x72, 0x64, 0x65, 0x72, 0x2e, 0x70, 0x62, 0x2e, 0x6d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x2e, 0x63,
	0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x53, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x52, 0x0c, 0x6f, 0x75,
	0x74, 0x70, 0x75, 0x74, 0x53, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x42, 0x06, 0x5a, 0x04, 0x77, 0x61,
	0x73, 0x6d, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_src_pb_module_wasm_wasm_proto_rawDescOnce sync.Once
	file_src_pb_module_wasm_wasm_proto_rawDescData = file_src_pb_module_wasm_wasm_proto_rawDesc
)

func file_src_pb_module_wasm_wasm_proto_rawDescGZIP() []byte {
	file_src_pb_module_wasm_wasm_proto_rawDescOnce.Do(func() {
		file_src_pb_module_wasm_wasm_proto_rawDescData = protoimpl.X.CompressGZIP(file_src_pb_module_wasm_wasm_proto_rawDescData)
	})
	return file_src_pb_module_wasm_wasm_proto_rawDescData
}

var file_src_pb_module_wasm_wasm_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_src_pb_module_wasm_wasm_proto_goTypes = []interface{}{
	(*Program)(nil),       // 0: tricorder.pb.module.wasm.Program
	(common.Format)(0),    // 1: tricorder.pb.module.common.Format
	(common.Lang)(0),      // 2: tricorder.pb.module.common.Lang
	(*common.Schema)(nil), // 3: tricorder.pb.module.common.Schema
}
var file_src_pb_module_wasm_wasm_proto_depIdxs = []int32{
	1, // 0: tricorder.pb.module.wasm.Program.fmt:type_name -> tricorder.pb.module.common.Format
	2, // 1: tricorder.pb.module.wasm.Program.lang:type_name -> tricorder.pb.module.common.Lang
	3, // 2: tricorder.pb.module.wasm.Program.output_schema:type_name -> tricorder.pb.module.common.Schema
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_src_pb_module_wasm_wasm_proto_init() }
func file_src_pb_module_wasm_wasm_proto_init() {
	if File_src_pb_module_wasm_wasm_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_src_pb_module_wasm_wasm_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Program); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_src_pb_module_wasm_wasm_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_src_pb_module_wasm_wasm_proto_goTypes,
		DependencyIndexes: file_src_pb_module_wasm_wasm_proto_depIdxs,
		MessageInfos:      file_src_pb_module_wasm_wasm_proto_msgTypes,
	}.Build()
	File_src_pb_module_wasm_wasm_proto = out.File
	file_src_pb_module_wasm_wasm_proto_rawDesc = nil
	file_src_pb_module_wasm_wasm_proto_goTypes = nil
	file_src_pb_module_wasm_wasm_proto_depIdxs = nil
}
