name: Setup
description: sets up helm lint and testing environment
inputs:
  create-kind-cluster:  # id of input
    description: 'Whether or not to create a kind cluster during setup'
    required: true
    default: "false"
runs:
  using: "composite"
  steps:
    - name: Set up Helm
      uses: azure/setup-helm@v3.4
      with:
        version: v3.9.0
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Set up chart-testing
      uses: helm/chart-testing-action@v2.3.0
    - name: Create kind cluster
      uses: helm/kind-action@v1.4.0
      if: ${{ inputs.create-kind-cluster == 'true' }}
    - name: Add Dependencies
      shell: bash
      run: |
          helm repo add timescale 'https://charts.timescale.com'
          helm repo add open-telemetry https://open-telemetry.github.io/opentelemetry-helm-charts
          helm repo add kube-prometheus-stack https://prometheus-community.github.io/helm-charts
          helm repo add grafana https://grafana.github.io/helm-charts
          helm dep up helm-charts/charts/**
