// Generated with command:
// ecc event.h --header-only && struct-bindgen event.bpf.o -p >event_bindgen.h

// Code generated by c-struct-bindgen and ecc - DO NOT EDIT
// See https://github.com/eunomia-bpf/c-struct-bindgen for details.
// struct-bindgen versions: 0.1.0
// source file path: event.bpf.o
#pragma once

#include <assert.h>
#include <stdint.h>
#include <string.h>

struct event_t {
  float F;
  char C;
  char __pad0[3];
  double D;
  int I;
  char __pad1[4];
  long long L;
  short Comm[13];
  char __pad2[6];
} __attribute__((packed));
