// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.14.0
// source: src/pb/module/ebpf/ebpf.proto

package ebpf

import (
	common "github.com/tricorder/src/pb/module/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ProbeSpec_Type int32

const (
	ProbeSpec_KPROBE        ProbeSpec_Type = 0
	ProbeSpec_SYSCALL_PROBE ProbeSpec_Type = 1
	ProbeSpec_UPROBE        ProbeSpec_Type = 2
	ProbeSpec_TRACEPOINT    ProbeSpec_Type = 3
	ProbeSpec_SAMPLE_PROBE  ProbeSpec_Type = 4
)

// Enum value maps for ProbeSpec_Type.
var (
	ProbeSpec_Type_name = map[int32]string{
		0: "KPROBE",
		1: "SYSCALL_PROBE",
		2: "UPROBE",
		3: "TRACEPOINT",
		4: "SAMPLE_PROBE",
	}
	ProbeSpec_Type_value = map[string]int32{
		"KPROBE":        0,
		"SYSCALL_PROBE": 1,
		"UPROBE":        2,
		"TRACEPOINT":    3,
		"SAMPLE_PROBE":  4,
	}
)

func (x ProbeSpec_Type) Enum() *ProbeSpec_Type {
	p := new(ProbeSpec_Type)
	*p = x
	return p
}

func (x ProbeSpec_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ProbeSpec_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_src_pb_module_ebpf_ebpf_proto_enumTypes[0].Descriptor()
}

func (ProbeSpec_Type) Type() protoreflect.EnumType {
	return &file_src_pb_module_ebpf_ebpf_proto_enumTypes[0]
}

func (x ProbeSpec_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ProbeSpec_Type.Descriptor instead.
func (ProbeSpec_Type) EnumDescriptor() ([]byte, []int) {
	return file_src_pb_module_ebpf_ebpf_proto_rawDescGZIP(), []int{0, 0}
}

type ProbeSpec struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type              ProbeSpec_Type `protobuf:"varint,1,opt,name=type,proto3,enum=tricorder.pb.module.ebpf.ProbeSpec_Type" json:"type,omitempty"`
	Target            string         `protobuf:"bytes,2,opt,name=target,proto3" json:"target,omitempty"`
	Entry             string         `protobuf:"bytes,3,opt,name=entry,proto3" json:"entry,omitempty"`
	Return            string         `protobuf:"bytes,4,opt,name=return,proto3" json:"return,omitempty"`
	SamplePeriodNanos int64          `protobuf:"varint,5,opt,name=sample_period_nanos,json=samplePeriodNanos,proto3" json:"sample_period_nanos,omitempty"`
	BinaryPath        string         `protobuf:"bytes,6,opt,name=binary_path,json=binaryPath,proto3" json:"binary_path,omitempty"`
}

func (x *ProbeSpec) Reset() {
	*x = ProbeSpec{}
	if protoimpl.UnsafeEnabled {
		mi := &file_src_pb_module_ebpf_ebpf_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProbeSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProbeSpec) ProtoMessage() {}

func (x *ProbeSpec) ProtoReflect() protoreflect.Message {
	mi := &file_src_pb_module_ebpf_ebpf_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProbeSpec.ProtoReflect.Descriptor instead.
func (*ProbeSpec) Descriptor() ([]byte, []int) {
	return file_src_pb_module_ebpf_ebpf_proto_rawDescGZIP(), []int{0}
}

func (x *ProbeSpec) GetType() ProbeSpec_Type {
	if x != nil {
		return x.Type
	}
	return ProbeSpec_KPROBE
}

func (x *ProbeSpec) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *ProbeSpec) GetEntry() string {
	if x != nil {
		return x.Entry
	}
	return ""
}

func (x *ProbeSpec) GetReturn() string {
	if x != nil {
		return x.Return
	}
	return ""
}

func (x *ProbeSpec) GetSamplePeriodNanos() int64 {
	if x != nil {
		return x.SamplePeriodNanos
	}
	return 0
}

func (x *ProbeSpec) GetBinaryPath() string {
	if x != nil {
		return x.BinaryPath
	}
	return ""
}

type Program struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Fmt            common.Format `protobuf:"varint,1,opt,name=fmt,proto3,enum=tricorder.pb.module.common.Format" json:"fmt,omitempty"`
	Lang           common.Lang   `protobuf:"varint,2,opt,name=lang,proto3,enum=tricorder.pb.module.common.Lang" json:"lang,omitempty"`
	Code           string        `protobuf:"bytes,3,opt,name=code,proto3" json:"code,omitempty"`
	PerfBufferName string        `protobuf:"bytes,4,opt,name=perf_buffer_name,json=perfBufferName,proto3" json:"perf_buffer_name,omitempty"`
	Probes         []*ProbeSpec  `protobuf:"bytes,5,rep,name=probes,proto3" json:"probes,omitempty"`
}

func (x *Program) Reset() {
	*x = Program{}
	if protoimpl.UnsafeEnabled {
		mi := &file_src_pb_module_ebpf_ebpf_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Program) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Program) ProtoMessage() {}

func (x *Program) ProtoReflect() protoreflect.Message {
	mi := &file_src_pb_module_ebpf_ebpf_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Program.ProtoReflect.Descriptor instead.
func (*Program) Descriptor() ([]byte, []int) {
	return file_src_pb_module_ebpf_ebpf_proto_rawDescGZIP(), []int{1}
}

func (x *Program) GetFmt() common.Format {
	if x != nil {
		return x.Fmt
	}
	return common.Format(0)
}

func (x *Program) GetLang() common.Lang {
	if x != nil {
		return x.Lang
	}
	return common.Lang(0)
}

func (x *Program) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *Program) GetPerfBufferName() string {
	if x != nil {
		return x.PerfBufferName
	}
	return ""
}

func (x *Program) GetProbes() []*ProbeSpec {
	if x != nil {
		return x.Probes
	}
	return nil
}

var File_src_pb_module_ebpf_ebpf_proto protoreflect.FileDescriptor

var file_src_pb_module_ebpf_ebpf_proto_rawDesc = []byte{
	0x0a, 0x1d, 0x73, 0x72, 0x63, 0x2f, 0x70, 0x62, 0x2f, 0x6d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x2f,
	0x65, 0x62, 0x70, 0x66, 0x2f, 0x65, 0x62, 0x70, 0x66, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x18, 0x74, 0x72, 0x69, 0x63, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x2e, 0x70, 0x62, 0x2e, 0x6d, 0x6f,
	0x64, 0x75, 0x6c, 0x65, 0x2e, 0x65, 0x62, 0x70, 0x66, 0x1a, 0x21, 0x73, 0x72, 0x63, 0x2f, 0x70,
	0x62, 0x2f, 0x6d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2f,
	0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xb5, 0x02, 0x0a,
	0x09, 0x50, 0x72, 0x6f, 0x62, 0x65, 0x53, 0x70, 0x65, 0x63, 0x12, 0x3c, 0x0a, 0x04, 0x74, 0x79,
	0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x28, 0x2e, 0x74, 0x72, 0x69, 0x63, 0x6f,
	0x72, 0x64, 0x65, 0x72, 0x2e, 0x70, 0x62, 0x2e, 0x6d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x2e, 0x65,
	0x62, 0x70, 0x66, 0x2e, 0x50, 0x72, 0x6f, 0x62, 0x65, 0x53, 0x70, 0x65, 0x63, 0x2e, 0x54, 0x79,
	0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x74, 0x61, 0x72, 0x67,
	0x65, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74,
	0x12, 0x14, 0x0a, 0x05, 0x65, 0x6e, 0x74, 0x72, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x65, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x74, 0x75, 0x72, 0x6e,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x65, 0x74, 0x75, 0x72, 0x6e, 0x12, 0x2e,
	0x0a, 0x13, 0x73, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x5f, 0x70, 0x65, 0x72, 0x69, 0x6f, 0x64, 0x5f,
	0x6e, 0x61, 0x6e, 0x6f, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x11, 0x73, 0x61, 0x6d,
	0x70, 0x6c, 0x65, 0x50, 0x65, 0x72, 0x69, 0x6f, 0x64, 0x4e, 0x61, 0x6e, 0x6f, 0x73, 0x12, 0x1f,
	0x0a, 0x0b, 0x62, 0x69, 0x6e, 0x61, 0x72, 0x79, 0x5f, 0x70, 0x61, 0x74, 0x68, 0x18, 0x06, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0a, 0x62, 0x69, 0x6e, 0x61, 0x72, 0x79, 0x50, 0x61, 0x74, 0x68, 0x22,
	0x53, 0x0a, 0x04, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0a, 0x0a, 0x06, 0x4b, 0x50, 0x52, 0x4f, 0x42,
	0x45, 0x10, 0x00, 0x12, 0x11, 0x0a, 0x0d, 0x53, 0x59, 0x53, 0x43, 0x41, 0x4c, 0x4c, 0x5f, 0x50,
	0x52, 0x4f, 0x42, 0x45, 0x10, 0x01, 0x12, 0x0a, 0x0a, 0x06, 0x55, 0x50, 0x52, 0x4f, 0x42, 0x45,
	0x10, 0x02, 0x12, 0x0e, 0x0a, 0x0a, 0x54, 0x52, 0x41, 0x43, 0x45, 0x50, 0x4f, 0x49, 0x4e, 0x54,
	0x10, 0x03, 0x12, 0x10, 0x0a, 0x0c, 0x53, 0x41, 0x4d, 0x50, 0x4c, 0x45, 0x5f, 0x50, 0x52, 0x4f,
	0x42, 0x45, 0x10, 0x04, 0x22, 0xf0, 0x01, 0x0a, 0x07, 0x50, 0x72, 0x6f, 0x67, 0x72, 0x61, 0x6d,
	0x12, 0x34, 0x0a, 0x03, 0x66, 0x6d, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x22, 0x2e,
	0x74, 0x72, 0x69, 0x63, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x2e, 0x70, 0x62, 0x2e, 0x6d, 0x6f, 0x64,
	0x75, 0x6c, 0x65, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x46, 0x6f, 0x72, 0x6d, 0x61,
	0x74, 0x52, 0x03, 0x66, 0x6d, 0x74, 0x12, 0x34, 0x0a, 0x04, 0x6c, 0x61, 0x6e, 0x67, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0e, 0x32, 0x20, 0x2e, 0x74, 0x72, 0x69, 0x63, 0x6f, 0x72, 0x64, 0x65, 0x72,
	0x2e, 0x70, 0x62, 0x2e, 0x6d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f,
	0x6e, 0x2e, 0x4c, 0x61, 0x6e, 0x67, 0x52, 0x04, 0x6c, 0x61, 0x6e, 0x67, 0x12, 0x12, 0x0a, 0x04,
	0x63, 0x6f, 0x64, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65,
	0x12, 0x28, 0x0a, 0x10, 0x70, 0x65, 0x72, 0x66, 0x5f, 0x62, 0x75, 0x66, 0x66, 0x65, 0x72, 0x5f,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x70, 0x65, 0x72, 0x66,
	0x42, 0x75, 0x66, 0x66, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x3b, 0x0a, 0x06, 0x70, 0x72,
	0x6f, 0x62, 0x65, 0x73, 0x18, 0x05, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x23, 0x2e, 0x74, 0x72, 0x69,
	0x63, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x2e, 0x70, 0x62, 0x2e, 0x6d, 0x6f, 0x64, 0x75, 0x6c, 0x65,
	0x2e, 0x65, 0x62, 0x70, 0x66, 0x2e, 0x50, 0x72, 0x6f, 0x62, 0x65, 0x53, 0x70, 0x65, 0x63, 0x52,
	0x06, 0x70, 0x72, 0x6f, 0x62, 0x65, 0x73, 0x42, 0x06, 0x5a, 0x04, 0x65, 0x62, 0x70, 0x66, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_src_pb_module_ebpf_ebpf_proto_rawDescOnce sync.Once
	file_src_pb_module_ebpf_ebpf_proto_rawDescData = file_src_pb_module_ebpf_ebpf_proto_rawDesc
)

func file_src_pb_module_ebpf_ebpf_proto_rawDescGZIP() []byte {
	file_src_pb_module_ebpf_ebpf_proto_rawDescOnce.Do(func() {
		file_src_pb_module_ebpf_ebpf_proto_rawDescData = protoimpl.X.CompressGZIP(file_src_pb_module_ebpf_ebpf_proto_rawDescData)
	})
	return file_src_pb_module_ebpf_ebpf_proto_rawDescData
}

var file_src_pb_module_ebpf_ebpf_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_src_pb_module_ebpf_ebpf_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_src_pb_module_ebpf_ebpf_proto_goTypes = []interface{}{
	(ProbeSpec_Type)(0), // 0: tricorder.pb.module.ebpf.ProbeSpec.Type
	(*ProbeSpec)(nil),   // 1: tricorder.pb.module.ebpf.ProbeSpec
	(*Program)(nil),     // 2: tricorder.pb.module.ebpf.Program
	(common.Format)(0),  // 3: tricorder.pb.module.common.Format
	(common.Lang)(0),    // 4: tricorder.pb.module.common.Lang
}
var file_src_pb_module_ebpf_ebpf_proto_depIdxs = []int32{
	0, // 0: tricorder.pb.module.ebpf.ProbeSpec.type:type_name -> tricorder.pb.module.ebpf.ProbeSpec.Type
	3, // 1: tricorder.pb.module.ebpf.Program.fmt:type_name -> tricorder.pb.module.common.Format
	4, // 2: tricorder.pb.module.ebpf.Program.lang:type_name -> tricorder.pb.module.common.Lang
	1, // 3: tricorder.pb.module.ebpf.Program.probes:type_name -> tricorder.pb.module.ebpf.ProbeSpec
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_src_pb_module_ebpf_ebpf_proto_init() }
func file_src_pb_module_ebpf_ebpf_proto_init() {
	if File_src_pb_module_ebpf_ebpf_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_src_pb_module_ebpf_ebpf_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProbeSpec); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_src_pb_module_ebpf_ebpf_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Program); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_src_pb_module_ebpf_ebpf_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_src_pb_module_ebpf_ebpf_proto_goTypes,
		DependencyIndexes: file_src_pb_module_ebpf_ebpf_proto_depIdxs,
		EnumInfos:         file_src_pb_module_ebpf_ebpf_proto_enumTypes,
		MessageInfos:      file_src_pb_module_ebpf_ebpf_proto_msgTypes,
	}.Build()
	File_src_pb_module_ebpf_ebpf_proto = out.File
	file_src_pb_module_ebpf_ebpf_proto_rawDesc = nil
	file_src_pb_module_ebpf_ebpf_proto_goTypes = nil
	file_src_pb_module_ebpf_ebpf_proto_depIdxs = nil
}
