
// Code generated by c-struct-bindgen and ecc - DO NOT EDIT
// See https://github.com/eunomia-bpf/c-struct-bindgen for details.
// struct-bindgen versions: 0.1.0
// source file path: event.bpf.o
#pragma once

#include <assert.h>
#include <stdint.h>
#include <string.h>

struct detectionPackets {
  unsigned long long nb_ddos_packets;
} __attribute__((packed));
