# Codelint is in super-linter, this includes linters not supported
# in super linter, and custom ones developed in house.
name: Additional lint
on:
  pull_request:
    branches:
      - main
permissions:
  contents: read
jobs:
  query-changed-files:
    name: List changed files
    # This matches the dev_image and base image used in the code base.
    runs-on: ubuntu-22.04
    outputs:
      any_ui_changed: ${{ steps.ui-changed.outputs.any_changed}}
      any_src_changed: ${{ steps.src-changed.outputs.any_changed}}
      any_go_changed: ${{ steps.go-changed.outputs.any_changed}}
    steps:
      - uses: actions/checkout@v3
        with:
          # Retrieve the preceding commit
          fetch-depth: 0
      - name: Get changed files under ui/
        id: ui-changed
        uses: tj-actions/changed-files@v35
        with:
          files: ui/**
      - name: Get changed files under src/
        id: src-changed
        uses: tj-actions/changed-files@v35
        with:
          files: src/**
      - name: Get changed files under src/
        id: go-changed
        uses: tj-actions/changed-files@v35
        with:
          files: src/**/*.go
      - name: DEBUG print src/ ui/ any_changed
        run: |
          echo "ui_code_changed: ${{ steps.ui-changed.outputs.any_changed }}"
          echo "src_code_changed: ${{ steps.src-changed.outputs.any_changed }}"
          echo "go_code_changed: ${{ steps.go-changed.outputs.any_changed }}"
  # Manually run yarn run eslint
  frontend-lint:
    name: Eslint
    runs-on: ubuntu-latest
    needs: query-changed-files
    if: needs.query-changed-files.outputs.any_ui_changed == 'true'
    defaults:
      run:
        working-directory: ./ui
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - run: yarn add eslint
      - run: yarn add eslint-plugin-unicorn
      - run: yarn add prettier
      - run: yarn run lint
  container-image-rules-lint:
    name: Must use custom container image rules
    runs-on: ubuntu-latest
    needs: query-changed-files
    if: needs.query-changed-files.outputs.any_src_changed == 'true'
    steps:
      - uses: actions/checkout@v3
      # Check that no one is using the native container_image rules
      - name: Custom container image rules
        run: .github/scripts/check_container_image_rules.sh
        shell: bash
  check-readme:
    name: Must have README.md
    runs-on: ubuntu-latest
    needs: query-changed-files
    if: needs.query-changed-files.outputs.any_src_changed == 'true'
    steps:
      - uses: actions/checkout@v3
      # Check that all directories under src/ have a README.md
      - name: Check README.md
        run: .github/scripts/check_readme.sh
        shell: bash
  check-readme:
    name: Markdown filenames
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      # Check that all markdown filenames are uppercase
      - name: Check markdown files
        run: .github/scripts/check_markdown_naming.sh
        shell: bash
  golangci-lint:
    name: Golangci-Lint
    runs-on: ubuntu-latest
    needs: query-changed-files
    # Disable for now as it always reports 3 files not gofmt-ed
    if: needs.query-changed-files.outputs.any_go_changed == 'true'
    steps:
      - uses: actions/checkout@v3
      # https://github.com/golangci/golangci-lint-action
      - name: Golangci Lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.47.3
          args: "--out-${NO_FUTURE}format colored-line-number"
          # Only check new changes
          only-new-issues: true
