name: Build and Push CI/Dev images

on:
  #TODO(jian): only for debug
  pull_request:
    branches:
      - main
  # Requires manual trigger
  # See https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#workflow_dispatch
  #workflow_dispatch:

env:
  DOCKER_HUB_REGISTRY: docker.io/tricorderobservability

jobs:
  build-and-push-base-build-image:
    name: Build and Push BASE-BUILD image
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v2.1.0
        with:
          registry: docker.io
          username: ${{ secrets.DOCKER_HUB_USER_NAME }}
          password: ${{ secrets.DOCKER_HUB_USER_PASSWORD }}
      - name: Build and Push
        run: ./devops/base_build_image/build_and_push.sh
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          file: ./devops/base_build_image/Dockerfile
          context: ./devops/base_build_image/
          tags: ${{ env.DOCKER_HUB_REGISTRY }}/base_build_image:v0.1
  build-and-push-ci-image:
    name: Build and Push CI image
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v2.1.0
        with:
          registry: docker.io
          username: ${{ secrets.DOCKER_HUB_USER_NAME }}
          password: ${{ secrets.DOCKER_HUB_USER_PASSWORD }}
      - name: Build and Push
        run: make -C devops/dev_image/ build_and_push_ci_image
  build-and-push-dev-image:
    name: Build and Push DEV image
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v2.1.0
        with:
          registry: docker.io
          username: ${{ secrets.DOCKER_HUB_USER_NAME }}
          password: ${{ secrets.DOCKER_HUB_USER_PASSWORD }}
      - name: Build and Push
        run: make -C devops/dev_image/ build_and_push_dev_image
