# https://github.com/bazelbuild/setup-bazelisk
name: Bazel build and test
on:
  pull_request:
    branches:
      - main
permissions:
  contents: read
jobs:
  query-changed-src-files:
    name: List changed files
    # This matches the dev_image and base image used in the code base.
    runs-on: ubuntu-22.04
    outputs:
      all: ${{ steps.src-changed.outputs.all_changed_files}}
      any_changed: ${{ steps.src-changed.outputs.any_changed}}
    steps:
      - uses: actions/checkout@v3
        with:
          # Retrieve the preceding commit
          fetch-depth: 0
      - name: Get changed files under src/
        id: src-changed
        uses: tj-actions/changed-files@v35
        with:
          files: src/**
      - name: DEBUG print changed files under src/
        run: |
          echo ${{ steps.src-changed.outputs.all_changed_files }}
          echo ${{ steps.src-changed.outputs.any_changed }}

  build-and-test:
    name: Bazel build and test
    # This matches the dev_image and base image used in the code base.
    runs-on: ubuntu-22.04
    # require the first job to have ran
    needs: query-changed-src-files
    # only run there are changed files
    if: needs.query-changed-src-files.outputs.any_changed == 'true'
    container:
      image: public.ecr.aws/tricorder/ci_image:202302140538
      options: --privileged
      volumes:
        # For accessing /sys/kernel/tracing/kprobe_events and other debugfs
        # entries.
        - /sys/kernel:/sys/kernel
    steps:
      - uses: actions/checkout@v3
        with:
          # Retrieve the preceding commit
          fetch-depth: 0
      - uses: bazelbuild/setup-bazelisk@v2
      - name: Query affected bazel rules
        id: q
        run: .github/scripts/bazel_ci_query.sh ${{ needs.query-changed-src-files.outputs.all }} >>$GITHUB_OUTPUT
        shell: bash
      - name: DEBUG print changed files under src/ and affected rules
        run: |
          echo ${{ needs.query-changed-src-files.outputs.any_changed }}
          echo ${{ needs.query-changed-src-files.outputs.all }}
          echo ${{ steps.q.outputs.any_affected }}
          echo ${{ steps.q.outputs.all }}
      - name: Bazel build affected rules
        if: steps.q.outputs.any_affected == 'true'
        run: .github/scripts/bazel.sh build --config=github-actions ${{ steps.q.outputs.all }}
        shell: bash
      - name: Bazel test affected rules
        if: steps.q.outputs.any_affected == 'true'
        run: .github/scripts/bazel_test.sh test --config=github-actions --flaky_test_attempts=3 ${{ steps.q.outputs.all }}
        shell: bash
      - name: Bazel test affected BPF rules
        if: steps.q.outputs.any_affected == 'true'
        run: .github/scripts/bazel_test.sh test --config=github-actions --flaky_test_attempts=3 --config=bpf --cache_test_results=no ${{ steps.q.outputs.all }}
        shell: bash
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
