name: Lint Helm Charts

on:
  pull_request:
    branches:
      - main

jobs:
  lint-test:
    name: Lint Helm Charts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: helm/chart-testing-action@v2.3.0
        run: ct lint --target-branch main --chart-dirs helm-charts/charts/**
