name: Lint Helm Charts

on:
  pull_request:
    branches:
      - main

jobs:
  lint-test:
    name: Lint Helm Charts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Helm
        uses: azure/setup-helm@v3.4
        with:
          version: v3.9.0
      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.3.0
      - name: Run chart-testing (lint)
        run: ct lint --target-branch main --chart-dirs helm-charts/charts/**
