name: Release Helm Charts

on:
  # Requires manual trigger
  # See https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#workflow_dispatch
  workflow_dispatch:

jobs:
  release-helm-charts:
    name: Release Helm Charts
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
      - name: Install Helm
        uses: azure/setup-helm@v3.1
        with:
          version: v3.4.1
      - name: Setup
        uses: ./.github/actions/setup
        with:
          create-kind-cluster: "false"
      - name: Release tricorder charts
        uses: helm/chart-releaser-action@v1.4.1
        with:
          charts_dir: helm-charts/charts
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          CR_RELEASE_NAME_TEMPLATE: "{{ .Version }}"
  release-gh-pages:
    name: Release GitHub pages
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Copy README.md To Branches Action
        uses: planetoftheweb/copy-to-branches@v1.2
        env:
          key: main
          branches: gh-pages
          files: README.md helm-charts/README.md helm-charts/docs
