name: Super Linter
# Individual linter configurations template:
# https://github.com/github/super-linter#template-rules-files
# Configs are under .github/linters

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Lint Code Base
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Write github env
        # Linters are disabled in this env file
        #
        # TODO(yaxiong): Go lint is disabled because golangci-lint produces false positive
        # because super linter runs each file against the linter, but some
        # linter has to work with the whole code base. See:
        # https://github.com/github/super-linter/issues/3596
        run: cat .github/super_linter.env >> "$GITHUB_ENV"

      - name: Lint Code Base
        # https://github.com/github/super-linter#slim-image
        # Linters missing from slim image are not useful for Tricorder codebase
        uses: github/super-linter/slim@v4
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
